#!/bin/sh

case "$1" in
	remove|abort-install|abort-upgrade)
		# This package is being removed, but its configuration has not yet
		# been purged.

		;;

	purge)
		insserv -rf homegear-gateway >/dev/null 2>&1
		rm -f /etc/homegear/gateway.conf > /dev/null 2>&1
		rm -Rf /var/log/homegear-gateway > /dev/null 2>&1
		rm -f /etc/init.d/homegear-gateway > /dev/null 2>&1
		rm -f /etc/logrotate.d/homegear-gateway > /dev/null 2>&1
        ;;

	disappear)
		;;

	upgrade)
		;;

	failed-upgrade)
		;;

	*) echo "$0: didn't understand being called with \`$1'" 1>&2
		exit 1;;
esac

exit 0

#DEBHELPER#
